### ISSUE TITLE
Read More button cropped on mobile

### ISSUE THREAD

**Issue by krisel** [alexneri/afhome-carousel#4] opened 2016-07-06 11:13 UTC
Please see screenshots below. Buttons are still cropped even vertically scrolled.

Device: iPhone 6
Browser: Safari

![image](https://cloud.githubusercontent.com/assets/20318068/16616087/763a6822-43ad-11e6-867c-91404fb4585e.png)

![image](https://cloud.githubusercontent.com/assets/20318068/16616092/7a8c14ca-43ad-11e6-9ae7-64d6c9ad981d.png)

**Comment by alexneri** [comment] 2016-07-06 12:25
Possibly something appearing only in Mobile. Will check actual dimensions in Safari Mobile in iPhone 6 viewport and see if padding is the cause of the problem.

**Comment by alexneri** [comment] 2016-07-06 12:30
Adjusted via commit# 416f7d218940db53b9db54e05b877310011af454

Ready for retest.

-A

**Comment by krisel** [comment] 2016-07-06 13:08
Buttons are displaying properly now. :D

![image](https://cloud.githubusercontent.com/assets/20318068/16618771/b61276c8-43bd-11e6-87fe-d7254554c30c.png)

![image](https://cloud.githubusercontent.com/assets/20318068/16618783/ba397044-43bd-11e6-808a-41c362618258.png)

**Comment by alexneri** [comment] 2016-07-06 15:04
Awesome, now closing. :+1:

**Closed as completed by alexneri** 2016-07-06 15:04 UTC
